-- ===========================================================================
-- V147 — Plantilla PERMANENTE del Plan General Contable (PGC PYMES).
--
-- Bloque REGISTRO (Benjamin 2026-06-26). V25 creó un pgc_template TEMPORARY y lo
-- dropeó tras sembrar las empresas existentes. Para el AUTO-REGISTRO (alta de una
-- asesoría/empresa nueva) hace falta una fuente PERMANENTE del PGC estándar: la
-- primera empresa de una BD limpia no puede copiarlo de nadie. Esta tabla es esa
-- fuente canónica; RegisterService siembra las cuentas estándar desde aquí.
--
-- Mismo contenido que el seed de V25 (PGC PYMES estándar). Idempotente.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS pgc_template (
    code VARCHAR(20) NOT NULL,
    name VARCHAR(180) NOT NULL,
    account_type VARCHAR(40) NOT NULL,
    PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO pgc_template (code, name, account_type) VALUES
-- Grupo 1: FINANCIACIÓN BÁSICA
('100', 'Capital social', 'EQUITY'),
('101', 'Fondo social', 'EQUITY'),
('102', 'Capital', 'EQUITY'),
('103', 'Socios por desembolsos no exigidos', 'EQUITY'),
('110', 'Prima de emisión o asunción', 'EQUITY'),
('112', 'Reserva legal', 'EQUITY'),
('113', 'Reservas voluntarias', 'EQUITY'),
('114', 'Reservas especiales', 'EQUITY'),
('118', 'Aportaciones de socios o propietarios', 'EQUITY'),
('120', 'Remanente', 'EQUITY'),
('121', 'Resultados negativos de ejercicios anteriores', 'EQUITY'),
('129', 'Resultado del ejercicio', 'EQUITY'),
('170', 'Deudas a largo plazo con entidades de crédito', 'LIABILITY'),
('171', 'Deudas a largo plazo', 'LIABILITY'),
('175', 'Efectos a pagar a largo plazo', 'LIABILITY'),

-- Grupo 2: INMOVILIZADO
('200', 'Investigación', 'ASSET'),
('201', 'Desarrollo', 'ASSET'),
('203', 'Propiedad industrial', 'ASSET'),
('206', 'Aplicaciones informáticas', 'ASSET'),
('210', 'Terrenos y bienes naturales', 'ASSET'),
('211', 'Construcciones', 'ASSET'),
('212', 'Instalaciones técnicas', 'ASSET'),
('213', 'Maquinaria', 'ASSET'),
('214', 'Utillaje', 'ASSET'),
('215', 'Otras instalaciones', 'ASSET'),
('216', 'Mobiliario', 'ASSET'),
('217', 'Equipos para procesos de información', 'ASSET'),
('218', 'Elementos de transporte', 'ASSET'),
('219', 'Otro inmovilizado material', 'ASSET'),
('280', 'Amortización acumulada del inmovilizado intangible', 'CONTRA'),
('281', 'Amortización acumulada del inmovilizado material', 'CONTRA'),

-- Grupo 3: EXISTENCIAS
('300', 'Mercaderías', 'ASSET'),
('310', 'Materias primas', 'ASSET'),
('320', 'Elementos y conjuntos incorporables', 'ASSET'),
('330', 'Productos en curso', 'ASSET'),
('340', 'Productos semiterminados', 'ASSET'),
('350', 'Productos terminados', 'ASSET'),
('360', 'Subproductos, residuos y materiales recuperados', 'ASSET'),
('390', 'Deterioro de valor de las mercaderías', 'CONTRA'),

-- Grupo 4: ACREEDORES Y DEUDORES (el más usado)
('400', 'Proveedores', 'LIABILITY'),
('401', 'Proveedores, efectos comerciales a pagar', 'LIABILITY'),
('406', 'Envases y embalajes a devolver a proveedores', 'LIABILITY'),
('407', 'Anticipos a proveedores', 'ASSET'),
('410', 'Acreedores por prestación de servicios', 'LIABILITY'),
('430', 'Clientes', 'ASSET'),
('431', 'Clientes, efectos comerciales a cobrar', 'ASSET'),
('436', 'Clientes de dudoso cobro', 'ASSET'),
('437', 'Envases y embalajes a devolver por clientes', 'ASSET'),
('438', 'Anticipos de clientes', 'LIABILITY'),
('440', 'Deudores', 'ASSET'),
('460', 'Anticipos de remuneraciones', 'ASSET'),
('465', 'Remuneraciones pendientes de pago', 'LIABILITY'),
('470', 'Hacienda Pública, deudor por diversos conceptos', 'ASSET'),
('471', 'Organismos de la Seguridad Social, deudores', 'ASSET'),
('472', 'Hacienda Pública, IVA soportado', 'ASSET'),
('473', 'Hacienda Pública, retenciones y pagos a cuenta', 'ASSET'),
('475', 'Hacienda Pública, acreedora por conceptos fiscales', 'LIABILITY'),
('476', 'Organismos de la Seguridad Social, acreedores', 'LIABILITY'),
('477', 'Hacienda Pública, IVA repercutido', 'LIABILITY'),
('480', 'Gastos anticipados', 'ASSET'),
('485', 'Ingresos anticipados', 'LIABILITY'),
('490', 'Deterioro de valor de créditos por operaciones comerciales', 'CONTRA'),

-- Grupo 5: CUENTAS FINANCIERAS
('500', 'Obligaciones y bonos a corto plazo', 'LIABILITY'),
('510', 'Deudas a corto plazo con partes vinculadas', 'LIABILITY'),
('520', 'Deudas a corto plazo con entidades de crédito', 'LIABILITY'),
('521', 'Deudas a corto plazo', 'LIABILITY'),
('523', 'Proveedores de inmovilizado a corto plazo', 'LIABILITY'),
('524', 'Acreedores por arrendamiento financiero a corto plazo', 'LIABILITY'),
('527', 'Intereses a corto plazo de deudas con entidades de crédito', 'LIABILITY'),
('540', 'Inversiones financieras a corto plazo en instrumentos de patrimonio', 'ASSET'),
('551', 'Cuenta corriente con socios y administradores', 'LIABILITY'),
('554', 'Cuenta corriente con otras partes vinculadas', 'LIABILITY'),
('555', 'Partidas pendientes de aplicación', 'ASSET'),
('570', 'Caja, euros', 'ASSET'),
('572', 'Bancos e instituciones de crédito c/c vista, euros', 'ASSET'),
('574', 'Bancos e instituciones de crédito, cuentas de ahorro', 'ASSET'),
('575', 'Inversiones a corto plazo de gran liquidez', 'ASSET'),

-- Grupo 6: COMPRAS Y GASTOS
('600', 'Compras de mercaderías', 'EXPENSE'),
('601', 'Compras de materias primas', 'EXPENSE'),
('602', 'Compras de otros aprovisionamientos', 'EXPENSE'),
('606', 'Descuentos sobre compras por pronto pago', 'EXPENSE'),
('607', 'Trabajos realizados por otras empresas', 'EXPENSE'),
('608', 'Devoluciones de compras y operaciones similares', 'EXPENSE'),
('609', 'Rappels por compras', 'EXPENSE'),
('610', 'Variación de existencias de mercaderías', 'EXPENSE'),
('620', 'Gastos en investigación y desarrollo del ejercicio', 'EXPENSE'),
('621', 'Arrendamientos y cánones', 'EXPENSE'),
('622', 'Reparaciones y conservación', 'EXPENSE'),
('623', 'Servicios de profesionales independientes', 'EXPENSE'),
('624', 'Transportes', 'EXPENSE'),
('625', 'Primas de seguros', 'EXPENSE'),
('626', 'Servicios bancarios y similares', 'EXPENSE'),
('627', 'Publicidad, propaganda y relaciones públicas', 'EXPENSE'),
('628', 'Suministros', 'EXPENSE'),
('629', 'Otros servicios', 'EXPENSE'),
('630', 'Impuesto sobre beneficios', 'EXPENSE'),
('631', 'Otros tributos', 'EXPENSE'),
('640', 'Sueldos y salarios', 'EXPENSE'),
('641', 'Indemnizaciones', 'EXPENSE'),
('642', 'Seguridad Social a cargo de la empresa', 'EXPENSE'),
('649', 'Otros gastos sociales', 'EXPENSE'),
('650', 'Pérdidas de créditos comerciales incobrables', 'EXPENSE'),
('660', 'Gastos financieros por actualización de provisiones', 'EXPENSE'),
('661', 'Intereses de obligaciones y bonos', 'EXPENSE'),
('662', 'Intereses de deudas', 'EXPENSE'),
('669', 'Otros gastos financieros', 'EXPENSE'),
('680', 'Amortización del inmovilizado intangible', 'EXPENSE'),
('681', 'Amortización del inmovilizado material', 'EXPENSE'),
('690', 'Pérdidas del inmovilizado intangible', 'EXPENSE'),
('691', 'Pérdidas del inmovilizado material', 'EXPENSE'),
('695', 'Dotación a la provisión para operaciones comerciales', 'EXPENSE'),

-- Grupo 7: VENTAS E INGRESOS
('700', 'Ventas de mercaderías', 'INCOME'),
('701', 'Ventas de productos terminados', 'INCOME'),
('702', 'Ventas de productos semiterminados', 'INCOME'),
('703', 'Ventas de subproductos y residuos', 'INCOME'),
('704', 'Ventas de envases y embalajes', 'INCOME'),
('705', 'Prestaciones de servicios', 'INCOME'),
('706', 'Descuentos sobre ventas por pronto pago', 'INCOME'),
('708', 'Devoluciones de ventas y operaciones similares', 'INCOME'),
('709', 'Rappels sobre ventas', 'INCOME'),
('710', 'Variación de existencias de productos en curso', 'INCOME'),
('740', 'Subvenciones, donaciones y legados a la explotación', 'INCOME'),
('747', 'Otras subvenciones', 'INCOME'),
('752', 'Ingresos por arrendamientos', 'INCOME'),
('753', 'Ingresos de propiedad industrial cedida en explotación', 'INCOME'),
('755', 'Ingresos por servicios al personal', 'INCOME'),
('759', 'Ingresos por servicios diversos', 'INCOME'),
('760', 'Ingresos de participaciones en instrumentos de patrimonio', 'INCOME'),
('762', 'Ingresos de créditos', 'INCOME'),
('769', 'Otros ingresos financieros', 'INCOME'),
('778', 'Ingresos excepcionales', 'INCOME');
