-- ===========================================================================
-- V46__pgc_pymes_complete.sql
--
-- PGC PYMES (Real Decreto 1515/2007) completo.
--
-- V25 sembró 131 cuentas núcleo. Esta migración añade ~250 más para
-- cubrir el Plan General Contable de PYMES en su totalidad — el
-- subconjunto del PGC normal (RD 1514/2007) que aplica a empresas
-- pequeñas y medianas. Es lo que la inmensa mayoría de asesorías y
-- empresarios necesitan; cubre los modelos AEAT 303, 130, 200, 347 y
-- 390 sin agujeros.
--
-- PGC normal (668 cuentas) queda como sub-slice PGC-FULL con importación
-- desde CSV bajo demanda — solo grandes empresas con contabilidad muy
-- detallada lo necesitan.
--
-- IDEMPOTENTE: usa INSERT ... ON DUPLICATE KEY UPDATE para no romper
-- si la cuenta ya estaba sembrada por V25.
--
-- COLLATE explícito en la temporal (mismo motivo que V25 y V44 —
-- MariaDB 11.4 cambió el default del servidor).
-- ===========================================================================

CREATE TEMPORARY TABLE pgc_pymes_template (
    code VARCHAR(20) NOT NULL,
    name VARCHAR(180) NOT NULL,
    account_type VARCHAR(40) NOT NULL,
    PRIMARY KEY (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO pgc_pymes_template (code, name, account_type) VALUES
-- ===========================================================================
-- GRUPO 1: FINANCIACIÓN BÁSICA — completar V25
-- ===========================================================================
('115', 'Reservas por pérdidas y ganancias actuariales', 'EQUITY'),
('116', 'Diferencias por ajuste capital euros', 'EQUITY'),
('117', 'Reservas de capitalización', 'EQUITY'),
('119', 'Diferencias por ajuste a valor razonable', 'EQUITY'),
('130', 'Subvenciones oficiales de capital', 'EQUITY'),
('131', 'Donaciones y legados de capital', 'EQUITY'),
('132', 'Otras subvenciones, donaciones y legados', 'EQUITY'),
('133', 'Ajustes por valoración en activos financieros', 'EQUITY'),
('134', 'Operaciones de cobertura', 'EQUITY'),
('135', 'Diferencias de conversión', 'EQUITY'),
('136', 'Ajustes por valoración de activos no corrientes en venta', 'EQUITY'),
('137', 'Ingresos fiscales a distribuir en varios ejercicios', 'EQUITY'),
('138', 'Ingresos fiscales por diferencias permanentes a distribuir', 'EQUITY'),
('140', 'Provisión por retribuciones a largo plazo al personal', 'LIABILITY'),
('141', 'Provisión para impuestos', 'LIABILITY'),
('142', 'Provisión para otras responsabilidades', 'LIABILITY'),
('143', 'Provisión por desmantelamiento, retiro o rehabilitación', 'LIABILITY'),
('145', 'Provisión para actuaciones medioambientales', 'LIABILITY'),
('146', 'Provisión para reestructuraciones', 'LIABILITY'),
('147', 'Provisión por transacciones con pagos basados en instrumentos', 'LIABILITY'),
('172', 'Deudas a largo plazo transformables en subvenciones', 'LIABILITY'),
('173', 'Proveedores de inmovilizado a largo plazo', 'LIABILITY'),
('174', 'Acreedores por arrendamiento financiero a largo plazo', 'LIABILITY'),
('176', 'Pasivos por derivados financieros a largo plazo', 'LIABILITY'),
('177', 'Obligaciones y bonos', 'LIABILITY'),
('178', 'Obligaciones y bonos convertibles', 'LIABILITY'),
('179', 'Deudas representadas en otros valores negociables', 'LIABILITY'),
('180', 'Fianzas recibidas a largo plazo', 'LIABILITY'),
('181', 'Anticipos recibidos por ventas a largo plazo', 'LIABILITY'),
('185', 'Depósitos recibidos a largo plazo', 'LIABILITY'),
('190', 'Acciones o participaciones emitidas', 'EQUITY'),
('192', 'Suscriptores de acciones', 'ASSET'),
('194', 'Capital emitido pendiente de inscripción', 'EQUITY'),

-- ===========================================================================
-- GRUPO 2: INMOVILIZADO
-- ===========================================================================
('200', 'Investigación', 'ASSET'),
('201', 'Desarrollo', 'ASSET'),
('202', 'Concesiones administrativas', 'ASSET'),
('203', 'Propiedad industrial', 'ASSET'),
('204', 'Fondo de comercio', 'ASSET'),
('205', 'Derechos de traspaso', 'ASSET'),
('206', 'Aplicaciones informáticas', 'ASSET'),
('209', 'Anticipos para inmovilizaciones intangibles', 'ASSET'),
('210', 'Terrenos y bienes naturales', 'ASSET'),
('211', 'Construcciones', 'ASSET'),
('212', 'Instalaciones técnicas', 'ASSET'),
('213', 'Maquinaria', 'ASSET'),
('214', 'Utillaje', 'ASSET'),
('215', 'Otras instalaciones', 'ASSET'),
('216', 'Mobiliario', 'ASSET'),
('217', 'Equipos para procesos de información', 'ASSET'),
('218', 'Elementos de transporte', 'ASSET'),
('219', 'Otro inmovilizado material', 'ASSET'),
('220', 'Inversiones en terrenos y bienes naturales', 'ASSET'),
('221', 'Inversiones en construcciones', 'ASSET'),
('230', 'Adaptación de terrenos y bienes naturales', 'ASSET'),
('231', 'Construcciones en curso', 'ASSET'),
('232', 'Instalaciones técnicas en montaje', 'ASSET'),
('233', 'Maquinaria en montaje', 'ASSET'),
('237', 'Equipos para procesos de información en montaje', 'ASSET'),
('239', 'Anticipos para inmovilizaciones materiales', 'ASSET'),
('240', 'Participaciones a largo plazo en partes vinculadas', 'ASSET'),
('241', 'Valores representativos de deuda a LP partes vinculadas', 'ASSET'),
('242', 'Créditos a largo plazo a partes vinculadas', 'ASSET'),
('250', 'Inversiones financieras a largo plazo en instrumentos patrimonio', 'ASSET'),
('251', 'Valores representativos de deuda a largo plazo', 'ASSET'),
('252', 'Créditos a largo plazo', 'ASSET'),
('253', 'Créditos a largo plazo por enajenación de inmovilizado', 'ASSET'),
('254', 'Créditos a largo plazo al personal', 'ASSET'),
('255', 'Activos por derivados financieros a largo plazo', 'ASSET'),
('258', 'Imposiciones a largo plazo', 'ASSET'),
('260', 'Fianzas constituidas a largo plazo', 'ASSET'),
('265', 'Depósitos constituidos a largo plazo', 'ASSET'),
('270', 'Gastos de formalización de deudas', 'ASSET'),
('280', 'Amortización acumulada del inmovilizado intangible', 'CONTRA'),
('281', 'Amortización acumulada del inmovilizado material', 'CONTRA'),
('282', 'Amortización acumulada de las inversiones inmobiliarias', 'CONTRA'),
('290', 'Deterioro de valor del inmovilizado intangible', 'CONTRA'),
('291', 'Deterioro de valor del inmovilizado material', 'CONTRA'),
('292', 'Deterioro de valor de las inversiones inmobiliarias', 'CONTRA'),

-- ===========================================================================
-- GRUPO 3: EXISTENCIAS
-- ===========================================================================
('300', 'Mercaderías A', 'ASSET'),
('301', 'Mercaderías B', 'ASSET'),
('310', 'Materias primas A', 'ASSET'),
('311', 'Materias primas B', 'ASSET'),
('320', 'Elementos y conjuntos incorporables', 'ASSET'),
('321', 'Combustibles', 'ASSET'),
('322', 'Repuestos', 'ASSET'),
('325', 'Materiales diversos', 'ASSET'),
('326', 'Embalajes', 'ASSET'),
('327', 'Envases', 'ASSET'),
('328', 'Material de oficina', 'ASSET'),
('330', 'Productos en curso A', 'ASSET'),
('340', 'Productos semiterminados A', 'ASSET'),
('350', 'Productos terminados A', 'ASSET'),
('360', 'Subproductos A', 'ASSET'),
('365', 'Residuos A', 'ASSET'),
('368', 'Materiales recuperados A', 'ASSET'),
('390', 'Deterioro de valor de las mercaderías', 'CONTRA'),

-- ===========================================================================
-- GRUPO 4: ACREEDORES Y DEUDORES (detalle 4 dígitos para AEAT)
-- ===========================================================================
('4000', 'Proveedores (euros)', 'LIABILITY'),
('4004', 'Proveedores (moneda extranjera)', 'LIABILITY'),
('4009', 'Proveedores, facturas pendientes recibir', 'LIABILITY'),
('401', 'Proveedores, efectos comerciales a pagar', 'LIABILITY'),
('403', 'Proveedores, empresas del grupo', 'LIABILITY'),
('404', 'Proveedores, empresas asociadas', 'LIABILITY'),
('405', 'Proveedores, otras partes vinculadas', 'LIABILITY'),
('406', 'Envases y embalajes a devolver a proveedores', 'ASSET'),
('407', 'Anticipos a proveedores', 'ASSET'),
('410', 'Acreedores por prestaciones de servicios', 'LIABILITY'),
('411', 'Acreedores, efectos comerciales a pagar', 'LIABILITY'),
('419', 'Acreedores por operaciones en común', 'LIABILITY'),
('4300', 'Clientes (euros)', 'ASSET'),
('4304', 'Clientes (moneda extranjera)', 'ASSET'),
('4309', 'Clientes, facturas pendientes formalizar', 'ASSET'),
('431', 'Clientes, efectos comerciales a cobrar', 'ASSET'),
('432', 'Clientes, operaciones de factoring', 'ASSET'),
('433', 'Clientes, empresas del grupo', 'ASSET'),
('434', 'Clientes, empresas asociadas', 'ASSET'),
('435', 'Clientes, otras partes vinculadas', 'ASSET'),
('436', 'Clientes de dudoso cobro', 'ASSET'),
('437', 'Envases y embalajes a devolver por clientes', 'LIABILITY'),
('438', 'Anticipos de clientes', 'LIABILITY'),
('440', 'Deudores', 'ASSET'),
('441', 'Deudores, efectos comerciales a cobrar', 'ASSET'),
('446', 'Deudores de dudoso cobro', 'ASSET'),
('447', 'Deudores, operaciones en común', 'ASSET'),
('449', 'Suministros pendientes facturar', 'LIABILITY'),
('460', 'Anticipos de remuneraciones', 'ASSET'),
('465', 'Remuneraciones pendientes de pago', 'LIABILITY'),
('466', 'Remuneraciones mediante sistemas de aportación definida pendientes', 'LIABILITY'),
('470', 'Hacienda Pública, deudora por diversos conceptos', 'ASSET'),
('4700', 'Hacienda Pública, deudora por IVA', 'ASSET'),
('4708', 'Hacienda Pública, deudora por subvenciones concedidas', 'ASSET'),
('4709', 'Hacienda Pública, deudora por devolución de impuestos', 'ASSET'),
('471', 'Organismos de la Seguridad Social, deudores', 'ASSET'),
('4720', 'Hacienda Pública, IVA soportado', 'ASSET'),
('4721', 'Hacienda Pública, IVA soportado en bienes corrientes y servicios', 'ASSET'),
('4722', 'Hacienda Pública, IVA soportado en bienes de inversión', 'ASSET'),
('4723', 'Hacienda Pública, IVA soportado en adquisiciones intracomunitarias', 'ASSET'),
('473', 'Hacienda Pública, retenciones y pagos a cuenta', 'ASSET'),
('474', 'Activos por impuesto diferido', 'ASSET'),
('4740', 'Activos por diferencias temporarias deducibles', 'ASSET'),
('4742', 'Derechos por deducciones y bonificaciones pendientes', 'ASSET'),
('4745', 'Crédito por pérdidas a compensar del ejercicio', 'ASSET'),
('475', 'Hacienda Pública, acreedora por conceptos fiscales', 'LIABILITY'),
('4750', 'Hacienda Pública, acreedora por IVA', 'LIABILITY'),
('4751', 'Hacienda Pública, acreedora por retenciones practicadas', 'LIABILITY'),
('4752', 'Hacienda Pública, acreedora por impuesto sobre sociedades', 'LIABILITY'),
('4758', 'Hacienda Pública, acreedora por subvenciones a reintegrar', 'LIABILITY'),
('476', 'Organismos de la Seguridad Social, acreedores', 'LIABILITY'),
('4770', 'Hacienda Pública, IVA repercutido', 'LIABILITY'),
('478', 'Pasivos por diferencias temporarias imponibles', 'LIABILITY'),
('479', 'Pasivos por impuesto diferido', 'LIABILITY'),
('480', 'Gastos anticipados', 'ASSET'),
('485', 'Ingresos anticipados', 'LIABILITY'),
('490', 'Deterioro de valor de créditos por operaciones comerciales', 'CONTRA'),
('493', 'Deterioro de valor de créditos a corto plazo a partes vinculadas', 'CONTRA'),
('499', 'Provisiones por operaciones comerciales', 'LIABILITY'),

-- ===========================================================================
-- GRUPO 5: CUENTAS FINANCIERAS
-- ===========================================================================
('500', 'Obligaciones y bonos a corto plazo', 'LIABILITY'),
('501', 'Obligaciones y bonos convertibles a corto plazo', 'LIABILITY'),
('505', 'Deudas representadas en otros valores negociables a CP', 'LIABILITY'),
('506', 'Intereses a corto plazo de empréstitos y otras emisiones', 'LIABILITY'),
('507', 'Dividendo activo a pagar', 'LIABILITY'),
('509', 'Valores negociables amortizados', 'LIABILITY'),
('510', 'Deudas a corto plazo con partes vinculadas', 'LIABILITY'),
('5105', 'Deudas a CP con entidades de crédito vinculadas', 'LIABILITY'),
('512', 'Acreedores por arrendamiento financiero a corto plazo', 'LIABILITY'),
('513', 'Proveedores de inmovilizado a corto plazo', 'LIABILITY'),
('514', 'Efectos a pagar a corto plazo a proveedores inmovilizado', 'LIABILITY'),
('516', 'Intereses a corto plazo de deudas con partes vinculadas', 'LIABILITY'),
('520', 'Deudas a corto plazo con entidades de crédito', 'LIABILITY'),
('5200', 'Préstamos a corto plazo de entidades de crédito', 'LIABILITY'),
('5208', 'Deudas por efectos descontados', 'LIABILITY'),
('521', 'Deudas a corto plazo', 'LIABILITY'),
('522', 'Deudas a corto plazo transformables en subvenciones', 'LIABILITY'),
('523', 'Proveedores de inmovilizado a corto plazo (no vinculados)', 'LIABILITY'),
('524', 'Acreedores por arrendamiento financiero a corto plazo (no vinculados)', 'LIABILITY'),
('525', 'Efectos a pagar a corto plazo', 'LIABILITY'),
('526', 'Dividendo activo a pagar', 'LIABILITY'),
('527', 'Intereses a corto plazo de deudas con entidades de crédito', 'LIABILITY'),
('528', 'Intereses a corto plazo de deudas', 'LIABILITY'),
('540', 'Inversiones financieras a corto plazo en instrumentos patrimonio', 'ASSET'),
('541', 'Valores representativos de deuda a corto plazo', 'ASSET'),
('542', 'Créditos a corto plazo', 'ASSET'),
('543', 'Créditos a corto plazo por enajenación de inmovilizado', 'ASSET'),
('544', 'Créditos a corto plazo al personal', 'ASSET'),
('545', 'Dividendo a cobrar', 'ASSET'),
('546', 'Intereses a corto plazo de valores representativos de deudas', 'ASSET'),
('547', 'Intereses a corto plazo de créditos', 'ASSET'),
('548', 'Imposiciones a corto plazo', 'ASSET'),
('550', 'Titular de la explotación', 'EQUITY'),
('551', 'Cuenta corriente con socios y administradores', 'ASSET'),
('552', 'Cuenta corriente con otras personas y entidades vinculadas', 'ASSET'),
('555', 'Partidas pendientes de aplicación', 'ASSET'),
('556', 'Desembolsos exigidos sobre participaciones', 'ASSET'),
('557', 'Dividendo activo a cuenta entregado en el ejercicio', 'EQUITY'),
('558', 'Socios por desembolsos exigidos', 'ASSET'),
('559', 'Derivados financieros a corto plazo', 'LIABILITY'),
('560', 'Fianzas recibidas a corto plazo', 'LIABILITY'),
('561', 'Depósitos recibidos a corto plazo', 'LIABILITY'),
('565', 'Fianzas constituidas a corto plazo', 'ASSET'),
('566', 'Depósitos constituidos a corto plazo', 'ASSET'),
('570', 'Caja, euros', 'ASSET'),
('571', 'Caja, moneda extranjera', 'ASSET'),
('572', 'Bancos e instituciones de crédito c/c vista, euros', 'ASSET'),
('573', 'Bancos e instituciones de crédito c/c vista, moneda extranjera', 'ASSET'),
('574', 'Bancos e instituciones de crédito, cuentas ahorro, euros', 'ASSET'),
('575', 'Bancos e instituciones de crédito, cuentas ahorro, moneda extranjera', 'ASSET'),
('576', 'Inversiones a corto plazo de gran liquidez', 'ASSET'),
('580', 'Activos no corrientes mantenidos para la venta', 'ASSET'),
('585', 'Provisiones asociadas a activos no corrientes para la venta', 'LIABILITY'),
('588', 'Pasivos asociados con activos no corrientes mantenidos para venta', 'LIABILITY'),

-- ===========================================================================
-- GRUPO 6: COMPRAS Y GASTOS — completar V25
-- ===========================================================================
('602', 'Compras de otros aprovisionamientos', 'EXPENSE'),
('606', 'Descuentos sobre compras por pronto pago', 'INCOME'),
('608', 'Devoluciones de compras y operaciones similares', 'INCOME'),
('609', 'Rappels por compras', 'INCOME'),
('610', 'Variación de existencias de mercaderías', 'EXPENSE'),
('611', 'Variación de existencias de materias primas', 'EXPENSE'),
('612', 'Variación de existencias de otros aprovisionamientos', 'EXPENSE'),
('620', 'Gastos en investigación y desarrollo del ejercicio', 'EXPENSE'),
('621', 'Arrendamientos y cánones', 'EXPENSE'),
('622', 'Reparaciones y conservación', 'EXPENSE'),
('623', 'Servicios de profesionales independientes', 'EXPENSE'),
('624', 'Transportes', 'EXPENSE'),
('625', 'Primas de seguros', 'EXPENSE'),
('626', 'Servicios bancarios y similares', 'EXPENSE'),
('627', 'Publicidad, propaganda y relaciones públicas', 'EXPENSE'),
('628', 'Suministros', 'EXPENSE'),
('629', 'Otros servicios', 'EXPENSE'),
('630', 'Impuesto sobre beneficios', 'EXPENSE'),
('631', 'Otros tributos', 'EXPENSE'),
('633', 'Ajustes negativos en imposición sobre beneficios', 'EXPENSE'),
('634', 'Ajustes negativos en IVA de activo corriente', 'EXPENSE'),
('636', 'Devolución de impuestos', 'INCOME'),
('638', 'Ajustes positivos en imposición sobre beneficios', 'INCOME'),
('639', 'Ajustes positivos en IVA de activo corriente', 'INCOME'),
('640', 'Sueldos y salarios', 'EXPENSE'),
('641', 'Indemnizaciones', 'EXPENSE'),
('642', 'Seguridad Social a cargo de la empresa', 'EXPENSE'),
('643', 'Retribuciones a largo plazo mediante sistemas aportación', 'EXPENSE'),
('644', 'Retribuciones a largo plazo mediante sistemas prestación', 'EXPENSE'),
('645', 'Retribuciones al personal mediante instrumentos patrimonio', 'EXPENSE'),
('649', 'Otros gastos sociales', 'EXPENSE'),
('650', 'Pérdidas de créditos comerciales incobrables', 'EXPENSE'),
('651', 'Resultados de operaciones en común', 'EXPENSE'),
('659', 'Otras pérdidas en gestión corriente', 'EXPENSE'),
('660', 'Gastos financieros por actualización de provisiones', 'EXPENSE'),
('661', 'Intereses de obligaciones y bonos', 'EXPENSE'),
('662', 'Intereses de deudas', 'EXPENSE'),
('663', 'Pérdidas por valoración de instrumentos financieros valor razonable', 'EXPENSE'),
('664', 'Gastos por dividendos de acciones o participaciones', 'EXPENSE'),
('665', 'Intereses por descuento de efectos y operaciones factoring', 'EXPENSE'),
('666', 'Pérdidas en participaciones y valores representativos de deuda', 'EXPENSE'),
('667', 'Pérdidas de créditos no comerciales', 'EXPENSE'),
('668', 'Diferencias negativas de cambio', 'EXPENSE'),
('669', 'Otros gastos financieros', 'EXPENSE'),
('670', 'Pérdidas procedentes del inmovilizado intangible', 'EXPENSE'),
('671', 'Pérdidas procedentes del inmovilizado material', 'EXPENSE'),
('672', 'Pérdidas procedentes de las inversiones inmobiliarias', 'EXPENSE'),
('673', 'Pérdidas procedentes de participaciones LP en partes vinculadas', 'EXPENSE'),
('675', 'Pérdidas por operaciones con obligaciones propias', 'EXPENSE'),
('678', 'Gastos excepcionales', 'EXPENSE'),
('680', 'Amortización del inmovilizado intangible', 'EXPENSE'),
('681', 'Amortización del inmovilizado material', 'EXPENSE'),
('682', 'Amortización de las inversiones inmobiliarias', 'EXPENSE'),
('690', 'Pérdidas por deterioro del inmovilizado intangible', 'EXPENSE'),
('691', 'Pérdidas por deterioro del inmovilizado material', 'EXPENSE'),
('692', 'Pérdidas por deterioro de las inversiones inmobiliarias', 'EXPENSE'),
('693', 'Pérdidas por deterioro de existencias', 'EXPENSE'),
('694', 'Pérdidas por deterioro de créditos por operaciones comerciales', 'EXPENSE'),
('695', 'Dotación a la provisión por operaciones comerciales', 'EXPENSE'),
('696', 'Pérdidas por deterioro de participaciones y valores representativos LP', 'EXPENSE'),
('697', 'Pérdidas por deterioro de créditos a LP', 'EXPENSE'),
('698', 'Pérdidas por deterioro de participaciones y valores representativos CP', 'EXPENSE'),
('699', 'Pérdidas por deterioro de créditos a CP', 'EXPENSE'),

-- ===========================================================================
-- GRUPO 7: VENTAS E INGRESOS — completar V25
-- ===========================================================================
('704', 'Ventas de envases y embalajes', 'INCOME'),
('705', 'Prestaciones de servicios', 'INCOME'),
('706', 'Descuentos sobre ventas por pronto pago', 'EXPENSE'),
('708', 'Devoluciones de ventas y operaciones similares', 'EXPENSE'),
('709', 'Rappels sobre ventas', 'EXPENSE'),
('710', 'Variación de existencias de productos en curso', 'INCOME'),
('711', 'Variación de existencias de productos semiterminados', 'INCOME'),
('712', 'Variación de existencias de productos terminados', 'INCOME'),
('713', 'Variación de existencias de subproductos, residuos y materiales recuperados', 'INCOME'),
('730', 'Trabajos realizados para el inmovilizado intangible', 'INCOME'),
('731', 'Trabajos realizados para el inmovilizado material', 'INCOME'),
('732', 'Trabajos realizados en inversiones inmobiliarias', 'INCOME'),
('733', 'Trabajos realizados para el inmovilizado material en curso', 'INCOME'),
('740', 'Subvenciones, donaciones y legados a la explotación', 'INCOME'),
('746', 'Subvenciones, donaciones y legados de capital traspasados a resultados', 'INCOME'),
('747', 'Otras subvenciones, donaciones y legados traspasados a resultados', 'INCOME'),
('751', 'Resultados de operaciones en común', 'INCOME'),
('752', 'Ingresos por arrendamientos', 'INCOME'),
('753', 'Ingresos de propiedad industrial cedida en explotación', 'INCOME'),
('754', 'Ingresos por comisiones', 'INCOME'),
('755', 'Ingresos por servicios al personal', 'INCOME'),
('759', 'Ingresos por servicios diversos', 'INCOME'),
('760', 'Ingresos de participaciones en instrumentos de patrimonio', 'INCOME'),
('761', 'Ingresos de valores representativos de deuda', 'INCOME'),
('762', 'Ingresos de créditos', 'INCOME'),
('763', 'Beneficios por valoración de instrumentos financieros valor razonable', 'INCOME'),
('765', 'Diferencias positivas de cambio', 'INCOME'),
('766', 'Beneficios en participaciones y valores representativos de deuda', 'INCOME'),
('767', 'Ingresos de activos afectos y de derechos de reembolso', 'INCOME'),
('768', 'Diferencias positivas de cambio', 'INCOME'),
('769', 'Otros ingresos financieros', 'INCOME'),
('770', 'Beneficios procedentes del inmovilizado intangible', 'INCOME'),
('771', 'Beneficios procedentes del inmovilizado material', 'INCOME'),
('772', 'Beneficios procedentes de las inversiones inmobiliarias', 'INCOME'),
('773', 'Beneficios procedentes de participaciones LP en partes vinculadas', 'INCOME'),
('775', 'Beneficios por operaciones con obligaciones propias', 'INCOME'),
('778', 'Ingresos excepcionales', 'INCOME'),
('790', 'Reversión del deterioro del inmovilizado intangible', 'INCOME'),
('791', 'Reversión del deterioro del inmovilizado material', 'INCOME'),
('792', 'Reversión del deterioro de inversiones inmobiliarias', 'INCOME'),
('793', 'Reversión del deterioro de existencias', 'INCOME'),
('794', 'Reversión del deterioro de créditos por operaciones comerciales', 'INCOME'),
('795', 'Exceso de provisiones', 'INCOME'),
('796', 'Reversión del deterioro de participaciones LP', 'INCOME'),
('797', 'Reversión del deterioro de créditos a LP', 'INCOME'),
('798', 'Reversión del deterioro de participaciones CP', 'INCOME'),
('799', 'Reversión del deterioro de créditos a CP', 'INCOME');

-- ---------------------------------------------------------------------------
-- Inserta para CADA empresa existente. Idempotente vía INSERT IGNORE:
-- si la cuenta ya existe (sembrada por V25), simplemente la omite. No
-- usamos ON DUPLICATE KEY UPDATE con SELECT + VALUES() porque MariaDB
-- 11.4 lanza error 1064 con esa combinación (la función VALUES() no es
-- reconocida sin la sintaxis nueva ... AS alias ON DUPLICATE ...). Las
-- cuentas que vienen aquí son código nuevo o, en el peor caso, el mismo
-- label que tenía V25 — no hace falta "actualizar" nada al re-sembrar.
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO accounting_accounts (id, company_id, code, name, account_type, active)
SELECT UUID(), c.id, t.code, t.name, t.account_type, TRUE
  FROM companies c
 CROSS JOIN pgc_pymes_template t;

DROP TEMPORARY TABLE pgc_pymes_template;
