-- ===========================================================================
-- V72__seed_benjamin_owner_pin — NEUTRALIZADA (decisión Benjamin 2026-06-26).
--
-- Esta migración sembraba DATOS DEMO/PRUEBA (empresas, usuarios, facturas,
-- nóminas, empleados de ejemplo). Para que el producto arranque LIMPIO —y el
-- primer arranque muestre el REGISTRO en vez del login— se vacía su contenido.
-- Se conserva el número de versión (no-op) para no romper la cadena Flyway;
-- Flyway repara el checksum en arranque (FlywayConfig.repairThenMigrate).
--
-- El histórico con los seeds demo queda en git si alguna vez se necesita para
-- desarrollo.
-- ===========================================================================
SELECT 1;
